component: website # [必选]要使用组件，更多组件请查看 https://github.com/serverless-components
name: notedly-web # [必选]组件实例名称
stage: prod # (可选) 用于区分环境信息，默认值是 dev

# ##website 组件配置##
# 更多内容请查看：https://github.com/serverless-components/tencent-website/blob/master/docs/configure.md
inputs:
  region: ap-shanghai # 部署目标地区。 更多参考 https://cloud.tencent.com/document/api/583/17238#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  protocol: https
  src: # 执行目录
    src: ./ # 本地需要打包的文件目录
    hook: npm run build:prod # 构建命令。在代码上传之前执行
    dist: ./dist # 输出的目录。如果配置 hook，此参数必填
    envPath: ./ # 生成的 env.js 存放路径。默认是当前工作路径。
  env: # 环境变量。会将 env 下配置的参数写入 env.js 文件，并一起打包上传。
    # 在 api 服务部署后获取 api 访问地址
    API_URI: https://service-qgecxkmj-1256173334.sh.apigw.tencentcs.com/release/api
  hosts:
    - host: notedly.ramen42.com # 希望配置的自定义域名
      https:
      switch: on
      http2: off
      certInfo:
        certId: 'abc'
